### ISSUE TITLE
Hook problems

### ISSUE THREAD

**Issue by EbenSorkin** [Fonthausen/NunitoSans_SSA#1]
<img width="1229" alt="image" src="https://github.com/Fonthausen/NunitoSans_SSA/assets/2181213/d8344fa0-35fb-40fb-a9f1-17b4dfd6694c">

The hook shape is mean to be a varient ( in the way that serifs are varied to suit circumstances ) of the 'f' shape. The f in Nunito is distinctive and not as hooked as we see in these two letters. The feeling of it should match.
There is another problem as well. It is a good idea to minimize the width of the f shape on the right side of 'd' because it will clash otherwise. It is a balancing act - wide enough to be noticed and clear but also minimizing clashes. In the case of 'b' it is the opposite. It should be relatively generous in width. The f in Nunito is aready fairly wide so a copy of that width is a good place to start.

**Comment by EbenSorkin** [comment]
Note too that this comment about bhook applies also to khook and hhook

**Comment by EbenSorkin** [comment]
and the comment about dhook applies to ghook

**Comment by Fonthausen** [comment]
@EbenSorkin I took your advise and reworked all the hooks. Hooks on b/h/k etc were made longer and look like the shape of the 'f'. The short hooks on d/g are narrowed/horizontally scaled version of the longer ones. The descending are based on the short ascending hooks. Thanks again for your help and advise.

<img width="1791" alt="Schermafbeelding 2023-11-01 om 21 58 26" src="https://github.com/Fonthausen/NunitoSans_SSA/assets/20181530/e1bfacbe-cd27-4f44-a575-f54d4453f7c7">


<img width="1791" alt="Schermafbeelding 2023-11-01 om 21 58 36" src="https://github.com/Fonthausen/NunitoSans_SSA/assets/20181530/8ee865b7-7a3a-491d-b962-63832c05aa18">


<img width="1791" alt="Schermafbeelding 2023-11-01 om 21 59 27" src="https://github.com/Fonthausen/NunitoSans_SSA/assets/20181530/583e9293-538c-45e5-9a7c-268898b55abf">


<img width="1791" alt="Schermafbeelding 2023-11-01 om 21 59 31" src="https://github.com/Fonthausen/NunitoSans_SSA/assets/20181530/b70e5eee-2403-4790-9dc3-b1a72fa30a5d">
