### ISSUE TITLE
CCMP - Cyrillic Beyond glyph set

### ISSUE THREAD

**Issue by EbenSorkin** [Fonthausen/NunitoSans_SSA#10]
These letters need top anchors or to have their top anchors placed correctly
Iu-cy 
Ia-cy 
Sha-cy
fita-cy
Ghestroke-cy 
Hardsign-cy
De-cy

These need bottom anchors fixed ( or fixed in some weights )
er-cy ( especially heavy )
Ge-cy

I am not clear how much of a priority fixing this is. But here is the info.

**Comment by Fonthausen** [comment]
> I am not clear how much of a priority fixing this is. But here is the info.

I corrected the anchors anyway. It wasn't much work
