### ISSUE TITLE
CCMP made letters - bugs - Latin SSA

### ISSUE THREAD

**Issue by EbenSorkin** [Fonthausen/NunitoSans_SSA#11]
Missing diacritic 
COMBINING DOUBLE MACRON BELOW U+035F

Missing letter
ɤ - ramshorn U+0264

misplaced anchor 
obarred
ubar

**Comment by Fonthausen** [comment]
> misplaced anchor
> obarred
> ubar

@EbenSorkin  How should the anchors be placed ? Or are some missing ?

**Comment by Fonthausen** [comment]
> Missing diacritic COMBINING DOUBLE MACRON BELOW U+035F
> 
> Missing letter ɤ - ramshorn U+0264

Both missing glyphs were added.

**Comment by EbenSorkin** [comment]
In some designs you can use the 'center' anchor for your bars and slashes but sometimes you need to use something arbitrary name for an anchor like 'midbar' or something like that. The bar that you need for stems is going to have a different width to the bar you need for a middle width letter like u or o and sometimes the o is wider than u and you need an o specific bar that is wide enough. Apologies if this is all obvious and I am somehow not getting to the core fo your question.

**Comment by Fonthausen** [comment]
> misplaced anchor
> obarred
> ubar

@EbenSorkin I added/renamed anchors to center.stroke and recomposed the glyphs.
