### ISSUE TITLE
missing localization 

### ISSUE THREAD

**Issue by EbenSorkin** [Fonthausen/NunitoSans_SSA#12]
vhook should also have these localizations

vhook.loclTOD0 
vhook.loclTOD0.ss01 
Vhook.loclTOD0 
Vhook.loclTOD0.ss01 

<img width="903" alt="image" src="https://github.com/Fonthausen/NunitoSans_SSA/assets/2181213/eb6652d9-ffeb-4cea-82c2-2c539c1d1373">

We should also have 
Esh.localGAD
Ezh.localGAD
Eng.loclNSM

<img width="784" alt="image" src="https://github.com/Fonthausen/NunitoSans_SSA/assets/2181213/93650a34-d61a-4c63-ad75-c65dfdc4421a">

**Comment by EbenSorkin** [comment]
I forgot Bhook.loclXPE which is a component based letter from Cyrillic : Be-cy

**Comment by Fonthausen** [comment]
@EbenSorkin It already contained vhook.loclTOD0.ss01. Since the cap height is equal to the ascender height I though I might not need Vhook.loclTOD0.ss01. I added one with the hook extending above cap heigth.

**Comment by Fonthausen** [comment]
> I forgot Bhook.loclXPE which is a component based letter from Cyrillic : Be-cy

Bhook.loclXPE was already in the font.

**Comment by Fonthausen** [comment]
I added Ezh.localGAD
 The file already contained Esh.localGAD and Eng.loclNSM.
