### ISSUE TITLE
stroke problems

### ISSUE THREAD

**Issue by EbenSorkin** [Fonthausen/NunitoSans_SSA#2]
<img width="970" alt="image" src="https://github.com/Fonthausen/NunitoSans_SSA/assets/2181213/4657bcb2-7e25-4f88-b302-d4738b725c47">

In general I am finding the scale of these strokes seems a bit too much

something more like 
<img width="298" alt="image" src="https://github.com/Fonthausen/NunitoSans_SSA/assets/2181213/709dd387-5811-4adf-a02d-4333c225cb40">

Seems closer to what I'm expecting.

In addition, I'd like to see the width and thickness regularized with the outside stroke made modest as it is in bar. 

I'd like to see the black strokes made more modest like this 

<img width="449" alt="image" src="https://github.com/Fonthausen/NunitoSans_SSA/assets/2181213/b5ed04f0-ce4b-4d1a-b7f3-702e657282c4">

In the light b and k examples the strokes are not yet long enough.

**Comment by Fonthausen** [comment]
@EbenSorkin Did I understood well, you would like the strokes to be liked the current ones in hbar and dcroat ? And the length of the right side more balanced over the weights ? And the thickness more modest in between the current strokes in hbar and (for example) bstroke ?

**Comment by EbenSorkin** [comment]
Yes.

**Comment by Fonthausen** [comment]
@EbenSorkin I balanced out the length, position and stroke thickness between the barred/stroked characters.

<img width="1234" alt="Schermafbeelding 2023-10-31 om 15 59 07" src="https://github.com/Fonthausen/NunitoSans_SSA/assets/20181530/16a167b5-b07b-4019-b5a5-21b6e7bd3c62">

<img width="1304" alt="Schermafbeelding 2023-10-31 om 15 58 48" src="https://github.com/Fonthausen/NunitoSans_SSA/assets/20181530/2e3008f1-a70d-402e-bc06-fd27625553fd">

**Comment by Fonthausen** [comment]
Here you can see the lowercase characters with a horizontal bar.

<img width="912" alt="Schermafbeelding 2023-10-31 om 16 04 29" src="https://github.com/Fonthausen/NunitoSans_SSA/assets/20181530/c76d8be9-3489-4ba7-988f-7e419d5dc645">

<img width="1080" alt="Schermafbeelding 2023-10-31 om 16 04 37" src="https://github.com/Fonthausen/NunitoSans_SSA/assets/20181530/b3413b24-c5c5-4a6a-ba5b-f8db224811da">
