### ISSUE TITLE
H Turned

### ISSUE THREAD

**Issue by EbenSorkin** [Fonthausen/NunitoSans_SSA#3]
The Hturned feels a little soft. I'd like to see the transition from middle bar to vertical stem on the right happen is a smaller space to create a boxier more structured feeling. I see this comes from the Che-cy as component but I suggest either revising the cyrillic letter or breaking the link with the component

<img width="398" alt="image" src="https://github.com/Fonthausen/NunitoSans_SSA/assets/2181213/06e4bc21-2b28-45e6-b09d-d106df33c870">

I'd like to see it more like this

<img width="350" alt="image" src="https://github.com/Fonthausen/NunitoSans_SSA/assets/2181213/7beda822-03d5-42e3-b207-d7b186b3a267">

**Comment by Fonthausen** [comment]
@EbenSorkin I corrected the Hturned. Mturned, Eng and Nlongrightleg were made in a similar style.
