### ISSUE TITLE
lc & diagonal stroke problems

### ISSUE THREAD

**Issue by EbenSorkin** [Fonthausen/NunitoSans_SSA#4]
These letters are a vexing problem that can never be good - only the least bad. 

That said, Denis has been clear that it is desirable that all the letters in this group take on a similar diagonal stroke so that they appear at least to be part of a system and the Danish øØ shares design intent with Ⱥⱥ, etc.

The problem is that o is open and a e are not, so the design circumstances are utterly different.

![image](https://github.com/Fonthausen/NunitoSans_SSA/assets/2181213/0d84221d-fb60-4149-97e6-1c96bc0c49fc)

Above, I am showing what happens if you take the diagonal stroke from ø and put it over the a - it basically goes black and unreadable. I am also showing a solution very roughly made where the a is adjusted to open its bowl and a pinched stroke is used.

It is also possible to force this stroke to be thinner than the others and to do something like the image below
<img width="771" alt="image" src="https://github.com/Fonthausen/NunitoSans_SSA/assets/2181213/33b6ce9a-9c9a-4803-af05-6cc9fa3c3ff6">

**Comment by EbenSorkin** [comment]
Weird, the first image wasn't what I expected. I should have looked like this 
<img width="778" alt="image" src="https://github.com/Fonthausen/NunitoSans_SSA/assets/2181213/9379b8b7-0b53-4696-ba5d-7d778bd1b148">

**Comment by Fonthausen** [comment]
@EbenSorkin Yes, that is one of the approaches I am intending to take.

**Comment by Fonthausen** [comment]
@EbenSorkin I changed the diagonal strokes the way you advised me.

**Comment by EbenSorkin** [comment]
I'll have a look this evening and make issues if I see stuff that looks
like it should be fixed.

What's your plan for kerning?

-e.

**Comment by Fonthausen** [comment]
> I'll have a look this evening and make issues if I see stuff that looks like it should be fixed. What's your plan for kerning?>

First combo's with punctuation and then using (your) African text samples to check for spacing issues.
