### ISSUE TITLE
belt diacritic issue

### ISSUE THREAD

**Issue by EbenSorkin** [Fonthausen/NunitoSans_SSA#6]
For reasons I have not been able to discover I am getting this message when I try to get a Glyphs app build of the font I get this error: 

Something went wrong when Removing Overlap in glyph:
lbelt.ss02

And that seems to be stopping a build from Glyphs app itself.

The base glyph and the belt diacritic both seem unproblematic. The same start points, anchors are present, correct shape order etc. So I am not sure why this is happening. I looked at _part.belt _part.belt.case _part.belt.lss02  

Could the issue be with the glyph name starting with an underscore?

I found when I decomposed the letter it still would not build. So I replaced the belts in the ones that would not remove overlap and decomposed them and them merged everything and that built.

Maybe recomposing all belt letters from scratch will solve it?

**Comment by Fonthausen** [comment]
> Could the issue be with the glyph name starting with an underscore?

Do you only het an error with the _part.belt... or with other _part... I used quite a lot of those.

**Comment by Fonthausen** [comment]
@EbenSorkin I decomposed and removed overlap in all uppercase and lowercase lbelt's just to avoid any issues.
